#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

SHARED_ENV_FILE="${CLAWDENTITY_SHARED_ENV_FILE:-$HOME/.clawdentity/worktree.env}"
if [[ "$SHARED_ENV_FILE" == ~/* ]]; then
  SHARED_ENV_FILE="$HOME/${SHARED_ENV_FILE#~/}"
fi

fail() {
  printf '[env:sync] error: %s\n' "$*" >&2
  exit 1
}

trim() {
  local value="$1"
  value="${value#"${value%%[![:space:]]*}"}"
  value="${value%"${value##*[![:space:]]}"}"
  printf '%s' "$value"
}

append_if_set() {
  local file_path="$1"
  local key="$2"
  local value="${3:-}"
  if [[ -n "$(trim "$value")" ]]; then
    printf '%s=%s\n' "$key" "$value" >> "$file_path"
  fi
}

write_header() {
  local file_path="$1"
  cat > "$file_path" <<EOF_HEADER
# Generated by scripts/env/sync-worktree-env.sh
# Source: $SHARED_ENV_FILE
# Do not edit directly. Update shared env source and run: pnpm env:sync

EOF_HEADER
}

if [[ ! -f "$SHARED_ENV_FILE" ]]; then
  fail "missing shared env source: $SHARED_ENV_FILE"
fi

set -a
# shellcheck disable=SC1090
source "$SHARED_ENV_FILE"
set +a

required_keys=(
  "CLAWDENTITY_REGISTRY_URL"
  "CLAWDENTITY_PROXY_URL"
  "BOOTSTRAP_SECRET"
  "BOOTSTRAP_INTERNAL_SERVICE_ID"
  "BOOTSTRAP_INTERNAL_SERVICE_SECRET"
  "REGISTRY_SIGNING_KEY"
  "REGISTRY_SIGNING_KEYS"
)

missing_keys=()
for key in "${required_keys[@]}"; do
  if [[ -z "$(trim "${!key:-}")" ]]; then
    missing_keys+=("$key")
  fi
done

if (( ${#missing_keys[@]} > 0 )); then
  fail "missing required keys in $SHARED_ENV_FILE: ${missing_keys[*]}"
fi

APP_VERSION="${APP_VERSION:-local-dev}"
DELIVERY_WEBHOOK_BASE_URL="${DELIVERY_WEBHOOK_BASE_URL:-http://127.0.0.1:19401}"
INJECT_IDENTITY_INTO_MESSAGE="${INJECT_IDENTITY_INTO_MESSAGE:-true}"
GITHUB_CLIENT_ID="${GITHUB_CLIENT_ID:-}"
GITHUB_CLIENT_SECRET="${GITHUB_CLIENT_SECRET:-}"
GITHUB_OAUTH_STATE_SECRET="${GITHUB_OAUTH_STATE_SECRET:-}"

ROOT_ENV_PATH="$REPO_ROOT/.env"
REGISTRY_ENV_PATH="$REPO_ROOT/apps/registry/.env"
PROXY_ENV_PATH="$REPO_ROOT/apps/proxy/.env"

write_header "$ROOT_ENV_PATH"
root_keys=(
  "CLAWDENTITY_REGISTRY_URL"
  "CLAWDENTITY_PROXY_URL"
  "BOOTSTRAP_INTERNAL_SERVICE_ID"
  "BOOTSTRAP_INTERNAL_SERVICE_SECRET"
  "CLAWDENTITY_API_KEY"
  "CLAWDENTITY_HUMAN_NAME"
  "CLAWDENTITY_PROXY_WS_URL"
  "CLAWDENTITY_CONNECTOR_BASE_URL"
  "CLAWDENTITY_CONNECTOR_OUTBOUND_PATH"
  "DELIVERY_WEBHOOK_BASE_URL"
  "DELIVERY_WEBHOOK_PATH"
  "DELIVERY_WEBHOOK_TOKEN"
  "DELIVERY_STATE_DIR"
)
for key in "${root_keys[@]}"; do
  append_if_set "$ROOT_ENV_PATH" "$key" "${!key:-}"
done

write_header "$REGISTRY_ENV_PATH"
append_if_set "$REGISTRY_ENV_PATH" "APP_VERSION" "$APP_VERSION"
append_if_set "$REGISTRY_ENV_PATH" "BOOTSTRAP_SECRET" "$BOOTSTRAP_SECRET"
append_if_set "$REGISTRY_ENV_PATH" "BOOTSTRAP_INTERNAL_SERVICE_ID" "$BOOTSTRAP_INTERNAL_SERVICE_ID"
append_if_set "$REGISTRY_ENV_PATH" "BOOTSTRAP_INTERNAL_SERVICE_SECRET" "$BOOTSTRAP_INTERNAL_SERVICE_SECRET"
append_if_set "$REGISTRY_ENV_PATH" "REGISTRY_SIGNING_KEY" "$REGISTRY_SIGNING_KEY"
append_if_set "$REGISTRY_ENV_PATH" "REGISTRY_SIGNING_KEYS" "$REGISTRY_SIGNING_KEYS"
append_if_set "$REGISTRY_ENV_PATH" "GITHUB_CLIENT_ID" "$GITHUB_CLIENT_ID"
append_if_set "$REGISTRY_ENV_PATH" "GITHUB_CLIENT_SECRET" "$GITHUB_CLIENT_SECRET"
append_if_set "$REGISTRY_ENV_PATH" "GITHUB_OAUTH_STATE_SECRET" "$GITHUB_OAUTH_STATE_SECRET"

write_header "$PROXY_ENV_PATH"
append_if_set "$PROXY_ENV_PATH" "APP_VERSION" "$APP_VERSION"
append_if_set "$PROXY_ENV_PATH" "DELIVERY_WEBHOOK_BASE_URL" "$DELIVERY_WEBHOOK_BASE_URL"
append_if_set "$PROXY_ENV_PATH" "BOOTSTRAP_INTERNAL_SERVICE_ID" "$BOOTSTRAP_INTERNAL_SERVICE_ID"
append_if_set "$PROXY_ENV_PATH" "BOOTSTRAP_INTERNAL_SERVICE_SECRET" "$BOOTSTRAP_INTERNAL_SERVICE_SECRET"
append_if_set "$PROXY_ENV_PATH" "INJECT_IDENTITY_INTO_MESSAGE" "$INJECT_IDENTITY_INTO_MESSAGE"

proxy_optional_keys=(
  "CRL_REFRESH_INTERVAL_MS"
  "CRL_MAX_AGE_MS"
  "CRL_STALE_BEHAVIOR"
  "AGENT_RATE_LIMIT_REQUESTS_PER_MINUTE"
  "AGENT_RATE_LIMIT_WINDOW_MS"
  "RELAY_QUEUE_MAX_MESSAGES_PER_AGENT"
  "RELAY_QUEUE_TTL_SECONDS"
  "RELAY_RETRY_INITIAL_MS"
  "RELAY_RETRY_MAX_MS"
  "RELAY_RETRY_MAX_ATTEMPTS"
  "RELAY_RETRY_JITTER_RATIO"
  "RELAY_MAX_IN_FLIGHT_DELIVERIES"
  "RELAY_MAX_FRAME_BYTES"
)
for key in "${proxy_optional_keys[@]}"; do
  append_if_set "$PROXY_ENV_PATH" "$key" "${!key:-}"
done

chmod 600 "$ROOT_ENV_PATH" "$REGISTRY_ENV_PATH" "$PROXY_ENV_PATH"

printf '[env:sync] updated:\n'
printf '  - %s\n' "$ROOT_ENV_PATH"
printf '  - %s\n' "$REGISTRY_ENV_PATH"
printf '  - %s\n' "$PROXY_ENV_PATH"
