export const CONNECTOR_VERSION = "0.0.0";

export const CONNECTOR_FRAME_VERSION = 1;

export const DEFAULT_OPENCLAW_HOOK_PATH = "/hooks/agent";
export const DEFAULT_OPENCLAW_BASE_URL = "http://127.0.0.1:18789";
export const DEFAULT_OPENCLAW_DELIVER_TIMEOUT_MS = 10_000;
export const DEFAULT_OPENCLAW_DELIVER_MAX_ATTEMPTS = 4;
export const DEFAULT_OPENCLAW_DELIVER_RETRY_INITIAL_DELAY_MS = 300;
export const DEFAULT_OPENCLAW_DELIVER_RETRY_MAX_DELAY_MS = 2_000;
export const DEFAULT_OPENCLAW_DELIVER_RETRY_BACKOFF_FACTOR = 2;

export const DEFAULT_HEARTBEAT_INTERVAL_MS = 30_000;
export const DEFAULT_RECONNECT_MIN_DELAY_MS = 1_000;
export const DEFAULT_RECONNECT_MAX_DELAY_MS = 30_000;
export const DEFAULT_RECONNECT_BACKOFF_FACTOR = 2;
export const DEFAULT_RECONNECT_JITTER_RATIO = 0.2;

export const DEFAULT_CONNECTOR_BASE_URL = "http://127.0.0.1:19400";
export const DEFAULT_CONNECTOR_OUTBOUND_PATH = "/v1/outbound";
export const DEFAULT_RELAY_DELIVER_TIMEOUT_MS = 15_000;
export const DEFAULT_OPENCLAW_DELIVER_RETRY_BUDGET_MS =
  DEFAULT_RELAY_DELIVER_TIMEOUT_MS - 1_000;

export const AGENT_ACCESS_HEADER = "x-claw-agent-access";

export const WS_READY_STATE_OPEN = 1;
