export const CONNECTOR_VERSION = "0.0.0";

export const CONNECTOR_FRAME_VERSION = 1;

export const DEFAULT_OPENCLAW_HOOK_PATH = "/hooks/agent";
export const DEFAULT_OPENCLAW_BASE_URL = "http://127.0.0.1:18789";
export const DEFAULT_OPENCLAW_DELIVER_TIMEOUT_MS = 10_000;
export const DEFAULT_OPENCLAW_DELIVER_MAX_ATTEMPTS = 4;
export const DEFAULT_OPENCLAW_DELIVER_RETRY_INITIAL_DELAY_MS = 300;
export const DEFAULT_OPENCLAW_DELIVER_RETRY_MAX_DELAY_MS = 2_000;
export const DEFAULT_OPENCLAW_DELIVER_RETRY_BACKOFF_FACTOR = 2;

export const DEFAULT_CONNECT_TIMEOUT_MS = 15_000;
export const DEFAULT_HEARTBEAT_INTERVAL_MS = 30_000;
export const DEFAULT_HEARTBEAT_ACK_TIMEOUT_MS = 60_000;
export const DEFAULT_RECONNECT_MIN_DELAY_MS = 1_000;
export const DEFAULT_RECONNECT_MAX_DELAY_MS = 30_000;
export const DEFAULT_RECONNECT_BACKOFF_FACTOR = 2;
export const DEFAULT_RECONNECT_JITTER_RATIO = 0.2;

export const DEFAULT_CONNECTOR_BASE_URL = "http://127.0.0.1:19400";
export const DEFAULT_CONNECTOR_OUTBOUND_PATH = "/v1/outbound";
export const DEFAULT_CONNECTOR_STATUS_PATH = "/v1/status";
export const DEFAULT_RELAY_DELIVER_TIMEOUT_MS = 15_000;
export const DEFAULT_OPENCLAW_DELIVER_RETRY_BUDGET_MS =
  DEFAULT_RELAY_DELIVER_TIMEOUT_MS - 1_000;
export const DEFAULT_CONNECTOR_INBOUND_INBOX_MAX_MESSAGES = 100_000;
export const DEFAULT_CONNECTOR_INBOUND_INBOX_MAX_BYTES = 2 * 1024 * 1024 * 1024;
export const DEFAULT_CONNECTOR_INBOUND_REPLAY_INTERVAL_MS = 2_000;
export const DEFAULT_CONNECTOR_INBOUND_REPLAY_BATCH_SIZE = 25;
export const DEFAULT_CONNECTOR_INBOUND_RETRY_INITIAL_DELAY_MS = 1_000;
export const DEFAULT_CONNECTOR_INBOUND_RETRY_MAX_DELAY_MS = 60_000;
export const DEFAULT_CONNECTOR_INBOUND_RETRY_BACKOFF_FACTOR = 2;
export const DEFAULT_CONNECTOR_INBOUND_EVENTS_MAX_ROWS = 10_000;
export const DEFAULT_CONNECTOR_INBOUND_DEAD_LETTER_NON_RETRYABLE_MAX_ATTEMPTS = 5;
export const DEFAULT_CONNECTOR_OPENCLAW_PROBE_INTERVAL_MS = 10_000;
export const DEFAULT_CONNECTOR_OPENCLAW_PROBE_TIMEOUT_MS = 3_000;
export const DEFAULT_CONNECTOR_RUNTIME_REPLAY_DELIVER_MAX_ATTEMPTS = 3;
export const DEFAULT_CONNECTOR_RUNTIME_REPLAY_DELIVER_RETRY_INITIAL_DELAY_MS = 2_000;
export const DEFAULT_CONNECTOR_RUNTIME_REPLAY_DELIVER_RETRY_MAX_DELAY_MS = 8_000;
export const DEFAULT_CONNECTOR_RUNTIME_REPLAY_DELIVER_RETRY_BACKOFF_FACTOR = 2;

export const AGENT_ACCESS_HEADER = "x-claw-agent-access";

export const WS_READY_STATE_OPEN = 1;
